/* ─── Translations ───────────────────────────────────────────────── */
const LANGS = {
  ru: {
    name:'Русский', flag:'🇷🇺',
    nav_home:'Главная', nav_week:'Аналитика', nav_lessons:'Уроки', nav_profile:'Профиль',
    greeting_done:'Записано сегодня', greeting_empty:'Начни трекинг',
    today:'Сегодня', streak:'Серия', week_activity:'Активность недели',
    week_budget:'Бюджет недели', spent:'Потрачено', of:'из',
    add_expense:'Добавить расход', recent:'Последние записи', show_all:'Показать все →',
    no_expenses:'Расходы ещё не добавлены',
    new_expense:'Новый расход', amount:'Сумма', category:'Категория',
    comment:'Комментарий', comment_hint:'Необязательно, например «кофе с другом»',
    save:'Записать расход', saved:'Записано!', coins_earned:'+10 монет',
    analytics:'Аналитика', by_category:'По категориям', by_day:'По дням',
    ai_report:'ИИ-анализ', get_report:'Получить отчёт', loading:'Анализируем...',
    budget_warn:'Вы близко к лимиту бюджета!',
    lessons:'Финансовые уроки', completed:'Пройдено',
    profile:'Профиль', level:'Уровень', coins:'Монет', entries:'Записей', days:'Дней',
    achievements:'Достижения', unlocked:'получено',
    budget_setting:'Недельный бюджет', edit:'Изменить', cancel:'Отмена', save_budget:'Сохранить',
    reset:'Сбросить данные', reset_warn:'Это удалит все ваши данные.',
    reset_btn:'Сбросить всё', reset_confirm:'Вы уверены? Все данные будут удалены!',
    lang_title:'Выберите язык', lang_cancel:'Отмена',
    budget_updated:'✓ Бюджет обновлён',
    logout:'Выйти', hi:'Привет',
    login:'Войти', register:'Регистрация',
    username:'Имя пользователя', password:'Пароль', confirm_password:'Повторите пароль',
    login_btn:'Войти в аккаунт', register_btn:'Создать аккаунт',
    no_account:'Нет аккаунта?', have_account:'Уже есть аккаунт?',
    sign_up:'Зарегистрироваться', sign_in:'Войти',
    err_user_exists:'Пользователь уже существует', err_user_not_found:'Пользователь не найден',
    err_wrong_password:'Неверный пароль', err_passwords_mismatch:'Пароли не совпадают',
    err_fill_all:'Заполните все поля', err_short:'Минимум 4 символа',
    welcome_back:'С возвращением', app_desc:'Управляй финансами с умом',
    remaining:'Осталось',
    cats:{food:'Еда',transport:'Транспорт',entertainment:'Развлечения',clothes:'Одежда',health:'Здоровье',coffee:'Кофе',other:'Прочее'},
    dayNames:['Вс','Пн','Вт','Ср','Чт','Пт','Сб'],
    levels:['Новичок','Экономист','Финансист','Эксперт','Гуру'],
    ach:{first_entry:{t:'Первый шаг',d:'Записал первую трату'},week_streak:{t:'7 дней подряд',d:'Серия 7 дней'},coins_100:{t:'Копилка',d:'100 монет'},entries_50:{t:'Привычка',d:'50 записей'}},
  },
  en: {
    name:'English', flag:'🇺🇸',
    nav_home:'Home', nav_week:'Analytics', nav_lessons:'Lessons', nav_profile:'Profile',
    greeting_done:'Logged today', greeting_empty:'Start tracking',
    today:'Today', streak:'Streak', week_activity:'Weekly activity',
    week_budget:'Weekly budget', spent:'Spent', of:'of',
    add_expense:'Add expense', recent:'Recent entries', show_all:'Show all →',
    no_expenses:'No expenses yet',
    new_expense:'New expense', amount:'Amount', category:'Category',
    comment:'Note', comment_hint:'Optional, e.g. "coffee with friend"',
    save:'Save expense', saved:'Saved!', coins_earned:'+10 coins',
    analytics:'Analytics', by_category:'By category', by_day:'By day',
    ai_report:'AI Report', get_report:'Get report', loading:'Analyzing...',
    budget_warn:'You are close to your budget limit!',
    lessons:'Financial lessons', completed:'Completed',
    profile:'Profile', level:'Level', coins:'Coins', entries:'Entries', days:'Days',
    achievements:'Achievements', unlocked:'unlocked',
    budget_setting:'Weekly budget', edit:'Edit', cancel:'Cancel', save_budget:'Save',
    reset:'Reset data', reset_warn:'This will delete all your data.',
    reset_btn:'Reset all', reset_confirm:'Are you sure? All data will be deleted!',
    lang_title:'Select language', lang_cancel:'Cancel',
    budget_updated:'✓ Budget updated',
    logout:'Logout', hi:'Hi',
    login:'Login', register:'Register',
    username:'Username', password:'Password', confirm_password:'Confirm password',
    login_btn:'Log in', register_btn:'Create account',
    no_account:"Don't have an account?", have_account:'Already have an account?',
    sign_up:'Sign up', sign_in:'Sign in',
    err_user_exists:'User already exists', err_user_not_found:'User not found',
    err_wrong_password:'Wrong password', err_passwords_mismatch:"Passwords don't match",
    err_fill_all:'Please fill all fields', err_short:'Minimum 4 characters',
    welcome_back:'Welcome back', app_desc:'Manage finances wisely',
    remaining:'Remaining',
    cats:{food:'Food',transport:'Transport',entertainment:'Entertainment',clothes:'Clothes',health:'Health',coffee:'Coffee',other:'Other'},
    dayNames:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
    levels:['Beginner','Economist','Analyst','Expert','Guru'],
    ach:{first_entry:{t:'First step',d:'Logged first expense'},week_streak:{t:'7-day streak',d:'7 days in a row'},coins_100:{t:'Piggy bank',d:'100 coins'},entries_50:{t:'Habit',d:'50 entries'}},
  },
  kz: {
    name:'Қазақша', flag:'🇰🇿',
    nav_home:'Басты', nav_week:'Аналитика', nav_lessons:'Сабақтар', nav_profile:'Профиль',
    greeting_done:'Бүгін тіркелді', greeting_empty:'Есепті бастаңыз',
    today:'Бүгін', streak:'Серия', week_activity:'Апталық белсенділік',
    week_budget:'Апталық бюджет', spent:'Жұмсалды', of:'/',
    add_expense:'Шығын қосу', recent:'Соңғы жазбалар', show_all:'Барлығын көру →',
    no_expenses:'Шығындар жоқ',
    new_expense:'Жаңа шығын', amount:'Сома', category:'Санат',
    comment:'Ескерту', comment_hint:'Міндетті емес',
    save:'Шығынды сақтау', saved:'Сақталды!', coins_earned:'+10 тиын',
    analytics:'Аналитика', by_category:'Санаттар бойынша', by_day:'Күндер бойынша',
    ai_report:'ЖИ-есеп', get_report:'Есеп алу', loading:'Талдауда...',
    budget_warn:'Бюджет лимитіне жақын!',
    lessons:'Қаржы сабақтары', completed:'Аяқталды',
    profile:'Профиль', level:'Деңгей', coins:'Тиын', entries:'Жазбалар', days:'Күн',
    achievements:'Жетістіктер', unlocked:'алынды',
    budget_setting:'Апталық бюджет', edit:'Өзгерту', cancel:'Болдырмау', save_budget:'Сақтау',
    reset:'Деректерді тастау', reset_warn:'Барлық деректер жойылады.',
    reset_btn:'Барлығын тастау', reset_confirm:'Сенімдісіз бе?',
    lang_title:'Тілді таңдаңыз', lang_cancel:'Болдырмау',
    budget_updated:'✓ Бюджет жаңартылды',
    logout:'Шығу', hi:'Сәлем',
    login:'Кіру', register:'Тіркелу',
    username:'Пайдаланушы аты', password:'Құпия сөз', confirm_password:'Құпия сөзді растаңыз',
    login_btn:'Аккаунтқа кіру', register_btn:'Аккаунт жасау',
    no_account:'Аккаунт жоқ па?', have_account:'Аккаунт бар ма?',
    sign_up:'Тіркелу', sign_in:'Кіру',
    err_user_exists:'Пайдаланушы бар', err_user_not_found:'Пайдаланушы табылмады',
    err_wrong_password:'Қате құпия сөз', err_passwords_mismatch:'Құпия сөздер сәйкес емес',
    err_fill_all:'Барлық өрістерді толтырыңыз', err_short:'Кемінде 4 таңба',
    welcome_back:'Қайта оралдыңыз', app_desc:'Қаржыны ақылды басқарыңыз',
    remaining:'Қалды',
    cats:{food:'Тамақ',transport:'Көлік',entertainment:'Ойын-сауық',clothes:'Киім',health:'Денсаулық',coffee:'Кофе',other:'Басқа'},
    dayNames:['Жк','Дс','Сс','Ср','Бс','Жм','Сн'],
    levels:['Жаңадан бастаушы','Экономист','Талдаушы','Маман','Гуру'],
    ach:{first_entry:{t:'Алғашқы қадам',d:'Бірінші шығынды тіркеді'},week_streak:{t:'7 күн қатарынан',d:'7 күндік серия'},coins_100:{t:'Үнемдеуші',d:'100 тиын'},entries_50:{t:'Дағды',d:'50 жазба'}},
  }
};

/* ─── Categories ─────────────────────────────────────────────────── */
const CATEGORIES = [
  {id:'food',icon:'ti-tools-kitchen-2',color:'#EF4444',bg:'rgba(239,68,68,0.12)'},
  {id:'transport',icon:'ti-car',color:'#3B82F6',bg:'rgba(59,130,246,0.12)'},
  {id:'entertainment',icon:'ti-device-gamepad-2',color:'#A78BFA',bg:'rgba(167,139,250,0.12)'},
  {id:'clothes',icon:'ti-hanger',color:'#F59E0B',bg:'rgba(245,158,11,0.12)'},
  {id:'health',icon:'ti-heart-rate-monitor',color:'#22C55E',bg:'rgba(34,197,94,0.12)'},
  {id:'coffee',icon:'ti-coffee',color:'#92400E',bg:'rgba(146,64,14,0.12)'},
  {id:'other',icon:'ti-dots-circle-horizontal',color:'#6B7280',bg:'rgba(107,114,128,0.12)'},
];

/* ─── Achievements ───────────────────────────────────────────────── */
const ACHIEVEMENTS = [
  {id:'first_entry', icon:'ti-target',  color:'var(--accent)', bg:'var(--accent-bg)', cond:s=>s.totalEntries>=1},
  {id:'week_streak', icon:'ti-flame',   color:'var(--red)',    bg:'var(--red-bg)',    cond:s=>s.streak>=7},
  {id:'coins_100',   icon:'ti-coin',    color:'var(--amber)',  bg:'var(--amber-bg)', cond:s=>s.coins>=100},
  {id:'entries_50',  icon:'ti-writing', color:'var(--green)',  bg:'var(--green-bg)', cond:s=>s.totalEntries>=50},
];

/* ─── Levels ─────────────────────────────────────────────────────── */
const LEVELS = [
  {min:0,      max:500,      icon:'ti-seedling'},
  {min:500,    max:1500,     icon:'ti-briefcase'},
  {min:1500,   max:3500,     icon:'ti-chart-line'},
  {min:3500,   max:7000,     icon:'ti-trophy'},
  {min:7000,   max:Infinity, icon:'ti-crown'},
];
